version: '3.8'

services:
  db:
    container_name: tenpista-bd
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      FRONTEND_URL: ${FRONTEND_URL}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./transactionstable.sql:/docker-entrypoint-initdb.d/transactionstable.sql:ro
    ports:
      - "5435:5432"
    restart: unless-stopped

  backend:
    container_name: tenpista-backend
    image: javierommel123/tenpista-transactions-api
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    container_name: tenpista-frontend
    build:
      context: ./tenpista-transactions-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      VITE_URL_BACKEND: ${VITE_URL_BACKEND}
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:

