CREATE TABLE IF NOT EXISTS public.transaction
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    amount integer NOT NULL,
    business varchar(100) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    tenpista_name varchar(100) NOT NULL,
    transaction_date timestamp(6) without time zone NOT NULL,
    CONSTRAINT transaction_pkey PRIMARY KEY (id)
);


ALTER TABLE IF EXISTS public.transaction
    OWNER to postgres;
    


INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (460, '2024-06-27 02:18:06', '2024-06-27 13:18:06', 'SuperMart', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (397, '2024-10-17 02:18:06', '2024-10-17 21:18:06', 'SuperMart', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (15, '2024-06-16 02:18:06', '2024-06-16 14:18:06', 'CityCenter', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (905, '2025-04-26 02:18:06', '2025-04-26 08:18:06', 'GlobalTech', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (807, '2024-12-08 02:18:06', '2024-12-08 14:18:06', 'MegaStore', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (408, '2025-02-15 02:18:06', '2025-02-15 08:18:06', 'FoodParadise', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (904, '2024-05-20 02:18:06', '2024-05-20 12:18:06', 'MegaStore', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (814, '2024-11-01 02:18:06', '2024-11-01 11:18:06', 'SuperMart', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (825, '2025-03-16 02:18:06', '2025-03-16 19:18:06', 'CityCenter', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (370, '2024-07-16 02:18:06', '2024-07-16 11:18:06', 'CityCenter', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (515, '2024-07-03 02:18:06', '2024-07-04 00:18:06', 'MegaStore', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (140, '2024-12-01 02:18:06', '2024-12-01 13:18:06', 'SuperMart', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (131, '2024-12-06 02:18:06', '2024-12-06 02:18:06', 'MegaStore', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (841, '2025-05-04 02:18:06', '2025-05-04 12:18:06', 'SuperMart', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (588, '2024-08-07 02:18:06', '2024-08-07 23:18:06', 'FoodParadise', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (317, '2025-03-05 02:18:06', '2025-03-05 09:18:06', 'SuperMart', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (161, '2024-06-22 02:18:06', '2024-06-22 15:18:06', 'SuperMart', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (662, '2024-06-16 02:18:06', '2024-06-16 11:18:06', 'FoodParadise', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (69, '2025-01-01 02:18:06', '2025-01-01 19:18:06', 'CityCenter', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (965, '2025-02-02 02:18:06', '2025-02-02 15:18:06', 'SuperMart', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (329, '2024-10-18 02:18:06', '2024-10-19 01:18:06', 'CityCenter', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (554, '2025-01-31 02:18:06', '2025-01-31 05:18:06', 'MegaStore', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (642, '2024-07-18 02:18:06', '2024-07-18 09:18:06', 'SuperMart', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (459, '2025-03-01 02:18:06', '2025-03-01 16:18:06', 'SuperMart', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (441, '2024-08-29 02:18:06', '2024-08-29 22:18:06', 'SuperMart', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (206, '2025-03-25 02:18:06', '2025-03-25 06:18:06', 'GlobalTech', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (73, '2024-09-14 02:18:06', '2024-09-14 08:18:06', 'CityCenter', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (710, '2024-10-29 02:18:06', '2024-10-29 21:18:06', 'SuperMart', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (267, '2024-06-08 02:18:06', '2024-06-08 04:18:06', 'SuperMart', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (234, '2025-03-09 02:18:06', '2025-03-09 02:18:06', 'CityCenter', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (371, '2025-02-11 02:18:06', '2025-02-11 09:18:06', 'MegaStore', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (436, '2025-04-10 02:18:06', '2025-04-11 00:18:06', 'GlobalTech', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (252, '2025-05-01 02:18:06', '2025-05-01 06:18:06', 'GlobalTech', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (856, '2024-11-25 02:18:06', '2024-11-25 05:18:06', 'FoodParadise', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (697, '2024-05-20 02:18:06', '2024-05-20 14:18:06', 'CityCenter', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (263, '2024-09-18 02:18:06', '2024-09-18 12:18:06', 'GlobalTech', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (653, '2024-07-31 02:18:06', '2024-07-31 21:18:06', 'MegaStore', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (314, '2025-01-01 02:18:06', '2025-01-01 19:18:06', 'FoodParadise', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (757, '2024-05-27 02:18:06', '2024-05-27 17:18:06', 'GlobalTech', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (811, '2024-07-03 02:18:06', '2024-07-03 08:18:06', 'SuperMart', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (208, '2024-11-22 02:18:06', '2024-11-23 02:18:06', 'FoodParadise', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (113, '2024-07-10 02:18:06', '2024-07-10 10:18:06', 'CityCenter', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (882, '2024-07-06 02:18:06', '2024-07-06 11:18:06', 'FoodParadise', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (747, '2024-05-22 02:18:06', '2024-05-22 21:18:06', 'CityCenter', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (418, '2024-08-23 02:18:06', '2024-08-23 20:18:06', 'CityCenter', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (194, '2024-11-25 02:18:06', '2024-11-25 04:18:06', 'CityCenter', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (938, '2025-02-19 02:18:06', '2025-02-19 03:18:06', 'CityCenter', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (994, '2024-10-11 02:18:06', '2024-10-11 11:18:06', 'FoodParadise', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (502, '2024-12-04 02:18:06', '2024-12-04 20:18:06', 'CityCenter', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (684, '2024-06-28 02:18:06', '2024-06-28 21:18:06', 'SuperMart', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (83, '2025-03-17 02:18:06', '2025-03-17 14:18:06', 'MegaStore', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (249, '2024-11-17 02:18:06', '2024-11-18 00:18:06', 'MegaStore', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (110, '2024-12-21 02:18:06', '2024-12-21 22:18:06', 'CityCenter', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (269, '2024-07-25 02:18:06', '2024-07-25 04:18:06', 'FoodParadise', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (74, '2024-08-02 02:18:06', '2024-08-03 01:18:06', 'CityCenter', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (649, '2024-12-30 02:18:06', '2024-12-30 02:18:06', 'SuperMart', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (787, '2024-12-01 02:18:06', '2024-12-01 16:18:06', 'GlobalTech', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (120, '2024-10-23 02:18:06', '2024-10-23 12:18:06', 'GlobalTech', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (630, '2024-06-05 02:18:06', '2024-06-05 09:18:06', 'CityCenter', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (116, '2024-12-18 02:18:06', '2024-12-18 11:18:06', 'SuperMart', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (688, '2025-01-30 02:18:06', '2025-01-30 18:18:06', 'GlobalTech', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (136, '2024-11-19 02:18:06', '2024-11-20 01:18:06', 'MegaStore', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (689, '2025-03-25 02:18:06', '2025-03-25 05:18:06', 'FoodParadise', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (560, '2025-04-26 02:18:06', '2025-04-26 16:18:06', 'MegaStore', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (544, '2025-02-14 02:18:06', '2025-02-14 15:18:06', 'SuperMart', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (881, '2024-09-07 02:18:06', '2024-09-08 01:18:06', 'MegaStore', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (263, '2024-12-14 02:18:06', '2024-12-14 03:18:06', 'FoodParadise', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (936, '2024-12-11 02:18:06', '2024-12-11 08:18:06', 'FoodParadise', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (116, '2025-03-18 02:18:06', '2025-03-18 17:18:06', 'GlobalTech', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (41, '2024-08-29 02:18:06', '2024-08-30 00:18:06', 'CityCenter', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (935, '2024-08-26 02:18:06', '2024-08-26 09:18:06', 'MegaStore', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (444, '2024-09-08 02:18:06', '2024-09-08 15:18:06', 'FoodParadise', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (585, '2024-06-19 02:18:06', '2024-06-19 16:18:06', 'FoodParadise', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (835, '2025-03-29 02:18:06', '2025-03-29 02:18:06', 'CityCenter', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (396, '2024-07-26 02:18:06', '2024-07-26 05:18:06', 'SuperMart', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (544, '2025-01-04 02:18:06', '2025-01-04 18:18:06', 'FoodParadise', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (863, '2024-09-28 02:18:06', '2024-09-28 17:18:06', 'FoodParadise', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (576, '2025-02-05 02:18:06', '2025-02-05 13:18:06', 'GlobalTech', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (492, '2024-12-22 02:18:06', '2024-12-22 17:18:06', 'FoodParadise', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (327, '2025-01-05 02:18:06', '2025-01-05 10:18:06', 'SuperMart', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (720, '2024-12-21 02:18:06', '2024-12-21 22:18:06', 'FoodParadise', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (205, '2024-05-27 02:18:06', '2024-05-28 00:18:06', 'FoodParadise', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (178, '2024-06-30 02:18:06', '2024-07-01 02:18:06', 'GlobalTech', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (625, '2025-01-08 02:18:06', '2025-01-08 16:18:06', 'CityCenter', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (200, '2024-05-18 02:18:06', '2024-05-18 13:18:06', 'FoodParadise', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (400, '2024-09-26 02:18:06', '2024-09-26 07:18:06', 'MegaStore', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (266, '2024-09-20 02:18:06', '2024-09-20 15:18:06', 'SuperMart', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (180, '2024-11-23 02:18:06', '2024-11-23 21:18:06', 'GlobalTech', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (970, '2025-02-06 02:18:06', '2025-02-06 14:18:06', 'FoodParadise', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (731, '2024-10-11 02:18:06', '2024-10-11 13:18:06', 'CityCenter', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (345, '2024-10-24 02:18:06', '2024-10-24 18:18:06', 'MegaStore', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (712, '2025-03-14 02:18:06', '2025-03-14 03:18:06', 'MegaStore', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (750, '2024-09-15 02:18:06', '2024-09-15 20:18:06', 'SuperMart', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (360, '2024-07-20 02:18:06', '2024-07-20 12:18:06', 'CityCenter', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (348, '2024-12-13 02:18:06', '2024-12-13 04:18:06', 'GlobalTech', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (684, '2024-08-16 02:18:06', '2024-08-16 09:18:06', 'SuperMart', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (852, '2024-05-20 02:18:06', '2024-05-20 06:18:06', 'SuperMart', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (395, '2024-06-16 02:18:06', '2024-06-16 16:18:06', 'MegaStore', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (579, '2024-12-31 02:18:06', '2024-12-31 14:18:06', 'MegaStore', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (100, '2025-04-12 02:18:06', '2025-04-12 22:18:06', 'SuperMart', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (951, '2024-11-03 02:18:06', '2024-11-03 06:18:06', 'SuperMart', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (512, '2025-03-05 02:18:06', '2025-03-05 09:18:06', 'CityCenter', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (791, '2024-11-26 02:18:06', '2024-11-26 03:18:06', 'CityCenter', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (195, '2024-09-01 02:18:06', '2024-09-01 13:18:06', 'FoodParadise', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (493, '2024-09-01 02:18:06', '2024-09-01 06:18:06', 'CityCenter', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (930, '2024-11-07 02:18:06', '2024-11-07 19:18:06', 'MegaStore', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (522, '2024-09-22 02:18:06', '2024-09-22 19:18:06', 'SuperMart', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (50, '2024-11-06 02:18:06', '2024-11-06 12:18:06', 'GlobalTech', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (419, '2024-11-30 02:18:06', '2024-12-01 00:18:06', 'MegaStore', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (961, '2024-09-17 02:18:06', '2024-09-17 18:18:06', 'MegaStore', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (507, '2024-09-03 02:18:06', '2024-09-03 15:18:06', 'FoodParadise', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (226, '2025-03-18 02:18:06', '2025-03-18 06:18:06', 'SuperMart', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (15, '2025-01-07 02:18:06', '2025-01-07 07:18:06', 'CityCenter', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (617, '2024-11-13 02:18:06', '2024-11-13 11:18:06', 'CityCenter', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (922, '2024-08-08 02:18:06', '2024-08-08 06:18:06', 'MegaStore', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (616, '2024-11-28 02:18:06', '2024-11-28 17:18:06', 'SuperMart', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (724, '2024-10-17 02:18:06', '2024-10-17 21:18:06', 'GlobalTech', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (634, '2024-12-22 02:18:06', '2024-12-22 21:18:06', 'CityCenter', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (531, '2025-05-08 02:18:06', '2025-05-09 02:18:06', 'MegaStore', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (924, '2024-08-18 02:18:06', '2024-08-18 15:18:06', 'CityCenter', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (148, '2024-06-12 02:18:06', '2024-06-12 10:18:06', 'SuperMart', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (977, '2024-10-07 02:18:06', '2024-10-07 11:18:06', 'GlobalTech', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (953, '2024-08-24 02:18:06', '2024-08-24 17:18:06', 'CityCenter', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (818, '2024-12-18 02:18:06', '2024-12-18 15:18:06', 'FoodParadise', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (460, '2024-12-11 02:18:06', '2024-12-11 06:18:06', 'FoodParadise', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (270, '2025-05-03 02:18:06', '2025-05-03 11:18:06', 'MegaStore', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (562, '2024-12-31 02:18:06', '2025-01-01 02:18:06', 'SuperMart', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (490, '2025-03-13 02:18:06', '2025-03-13 07:18:06', 'SuperMart', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (869, '2024-08-25 02:18:06', '2024-08-25 21:18:06', 'MegaStore', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (482, '2024-09-29 02:18:06', '2024-09-29 15:18:06', 'GlobalTech', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (357, '2025-01-29 02:18:06', '2025-01-29 18:18:06', 'CityCenter', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (285, '2024-08-22 02:18:06', '2024-08-22 17:18:06', 'SuperMart', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (986, '2024-07-27 02:18:06', '2024-07-27 05:18:06', 'GlobalTech', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (186, '2025-02-17 02:18:06', '2025-02-17 06:18:06', 'GlobalTech', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (693, '2024-08-01 02:18:06', '2024-08-01 08:18:06', 'GlobalTech', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (646, '2025-04-03 02:18:06', '2025-04-03 14:18:06', 'CityCenter', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (765, '2024-06-21 02:18:06', '2024-06-21 21:18:06', 'SuperMart', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (771, '2024-09-02 02:18:06', '2024-09-02 11:18:06', 'SuperMart', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (417, '2025-02-23 02:18:06', '2025-02-23 11:18:06', 'CityCenter', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (246, '2024-05-24 02:18:06', '2024-05-24 16:18:06', 'FoodParadise', 'HQ Office');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (742, '2025-03-24 02:18:06', '2025-03-24 08:18:06', 'FoodParadise', 'Warehouse X');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (652, '2024-09-08 02:18:06', '2024-09-08 17:18:06', 'CityCenter', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (638, '2025-01-26 02:18:06', '2025-01-26 09:18:06', 'FoodParadise', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (465, '2024-06-25 02:18:06', '2024-06-25 15:18:06', 'GlobalTech', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (963, '2025-01-28 02:18:06', '2025-01-28 05:18:06', 'GlobalTech', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (737, '2025-04-18 02:18:06', '2025-04-18 09:18:06', 'SuperMart', 'Branch A');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (725, '2024-08-20 02:18:06', '2024-08-20 03:18:06', 'FoodParadise', 'Online Store');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (885, '2024-10-18 02:18:06', '2024-10-18 19:18:06', 'SuperMart', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (907, '2024-07-22 02:18:06', '2024-07-22 17:18:06', 'FoodParadise', 'Branch B');
        

INSERT INTO public.transaction (amount, created_at, transaction_date, business, tenpista_name)
VALUES (485, '2024-08-15 02:18:06', '2024-08-15 09:18:06', 'SuperMart', 'Online Store');


