spring:
  application:
    name: tenpista-transactions-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/transactionsdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false  
server:
  port: 8081
  
cors:
  allowed-origins: ${FRONTEND_URL:http://localhost:5173}

logging:
  level:
    root: DEBUG
